httpProxy: "http://127.0.0.1:10809"

httpsProxy: "http://127.0.0.1:10809"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.3.1.cjs
